//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuzzOn.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuzzOn.UI.Resources.WebApiResources", typeof(WebApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/Itinerario/BuscarPontos/{codigo}/{token}.
        /// </summary>
        internal static string BuscarPontos {
            get {
                return ResourceManager.GetString("BuscarPontos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/Itinerario/BuscarRota/{codigo}/{token}.
        /// </summary>
        internal static string BuscarRota {
            get {
                return ResourceManager.GetString("BuscarRota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/MobileApi/Cadastro/Concluir/{token}.
        /// </summary>
        internal static string ConcluirCadastro {
            get {
                return ResourceManager.GetString("ConcluirCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/MobileApi/Inicio/DadosIniciais/WindowsPhone.
        /// </summary>
        internal static string DadosIniciais {
            get {
                return ResourceManager.GetString("DadosIniciais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/MobileApi/Mensagem/EnviarMensagem/{mensagemUsuario}/{token}.
        /// </summary>
        internal static string FaleConosco {
            get {
                return ResourceManager.GetString("FaleConosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/Itinerario/Buscar/{codigo}/{token}.
        /// </summary>
        internal static string Itinerario {
            get {
                return ResourceManager.GetString("Itinerario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/MobileApi/Update/LinhasHorariosVersoes/{token}.
        /// </summary>
        internal static string LinhasHorariosVersoes {
            get {
                return ResourceManager.GetString("LinhasHorariosVersoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/Saldo/Consultar/{ct}/{cpf}/{token}.
        /// </summary>
        internal static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/MobileApi/Versoes/ListarVersaoLinhasHorarios/{token}.
        /// </summary>
        internal static string TabelaVersoesLinhasHorarios {
            get {
                return ResourceManager.GetString("TabelaVersoesLinhasHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.buzzon.com.br/Itinerario/Versao/{codigo}/{token}.
        /// </summary>
        internal static string VersaoItinerario {
            get {
                return ResourceManager.GetString("VersaoItinerario", resourceCulture);
            }
        }
    }
}
